#!/bin/bash
# Edition : Stable Edition V2.0
# Auther  : Muh Aripin Ilham
# (C) Copyright 2023-2024 By  Under Tunnel
# =========================================
#!/bin/bash
g=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 2)
gb=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 3)
b=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 4)
p=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 5)
r=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 6)
y=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 7)
MYIP=$(wget -qO- ipv4.icanhazip.com);
repo=https://raw.githubusercontent.com/gazzent/ip/main/ip
ipsaya=$(wget -qO- ipv4.icanhazip.com);
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
useexp=$(wget -qO- ${repo} | grep $ipsaya | awk '{print $4}')
if [[ $date_list < $useexp ]]; then
echo -ne
else
echo -e "${g}────────────────────────────────────────────${p}"
echo -e "${b}          404 NOT FOUND AUTOSCRIPT          ${p}"
echo -e "${g}────────────────────────────────────────────${p}"
echo -e ""
echo -e "            ${r}PERMISSION DENIED OR!${p}"
echo -e "   ${y}Your VPS${p} $ipsaya ${y}Expired${p}"
echo -e "     ${y}Buy access permissions for scripts${p}"
echo -e "             ${y}Contact Admin :${p}"
echo -e "      ${gb}Telegram${p} t.me/mehonk_mt"
echo -e "${g}────────────────────────────────────────────${p}"
exit
fi
echo "Loading..."
red() { echo -e "\033[32;1m${*}\${p}"; }
domain=$(cat /etc/xray/domain)
PUB=$(cat /etc/slowdns/server.pub)
CITY=$(cat /etc/xray/city)
NS=$(cat /etc/xray/dns)
clear
add_all() (
clear
until [[ $user =~ ^[a-zA-Z0-9_]+$ && ${CLIENT_EXISTS} == '0' ]]; do
echo -e "${g}┌──────────────────────────────────────────┐${p}"
echo -e "${g}│${b}       Add Vless Ws & gRPC Account        ${p}"
echo -e "${g}└──────────────────────────────────────────┘${p}"
read -p "Username : " user
CLIENT_EXISTS=$(grep -w $user /etc/xray/config.json | wc -l)
if [[ ${CLIENT_EXISTS} == '1' ]]; then
clear
echo -e "${g}┌──────────────────────────────────────────┐${p}"
echo ""
echo "      A client name was already created"
echo ""
echo -e "${g}└──────────────────────────────────────────┘${p}"
read -n 1 -s -r -p "Press [ Enter ] to back on menu"
menu
fi
done
uuid=$(cat /proc/sys/kernel/random/uuid)
read -p "Expired (days): " masaaktif
read -p "Limit Quota (GB): " Quota
read -p "Limit User (IP): " iplim
exp=$(date -d "$masaaktif days" +"%Y-%m-%d")
sed -i '/#vless$/a\#vl# '"$user $exp"'\
},{"id": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
sed -i '/#vlessgrpc$/a\#vl# '"$user $exp"'\
},{"id": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
cat >/var/www/html/vless-$user.txt <<-END
-----------------------------------------
UnderTunnel PROJECT
-----------------------------------------
Format Vless WS (TLS)
-----------------------------------------
- name: Vless-$user
server: ${domain}
port: 443
type: vless
uuid: ${uuid}
cipher: auto
tls: true
skip-cert-verify: true
servername: ${domain}
network: ws
ws-opts:
path: /vless
headers:
Host: ${domain}
udp: true
-----------------------------------------
Format Vless WS (NTLS)
-----------------------------------------
- name: Vless-$user
server: ${domain}
port: 80
type: vless
uuid: ${uuid}
cipher: auto
tls: false
skip-cert-verify: false
servername: ${domain}
network: ws
ws-opts:
path: /vless
headers:
Host: ${domain}
udp: true
-----------------------------------------
Format Vless gRPC (SNI)
-----------------------------------------
- name: Vless-$user
server: ${domain}
port: 443
type: vless
uuid: ${uuid}
cipher: auto
tls: true
skip-cert-verify: true
servername: ${domain}
network: grpc
grpc-opts:
grpc-mode: gun
grpc-service-name: vless-grpc
udp: true
-----------------------------------------
Link Vless Account
-----------------------------------------
Link TLS : vless://${uuid}@${domain}:443?path=/vless&security=tls&encryption=none&type=ws#${user}
-----------------------------------------
Link NTLS : vless://${uuid}@${domain}:80?path=/vless&encryption=none&type=ws#${user}
-----------------------------------------
Link GRPC : vless://${uuid}@${domain}:443?mode=gun&security=tls&encryption=none&type=grpc&serviceName=vless-grpc&sni=${domain}#${user}
-----------------------------------------
END
vlesslink1="vless://${uuid}@${domain}:443?path=/vless&security=tls&encryption=none&type=ws#${user}"
vlesslink2="vless://${uuid}@${domain}:80?path=/vless&encryption=none&type=ws#${user}"
vlesslink3="vless://${uuid}@${domain}:443?mode=gun&security=tls&encryption=none&type=grpc&serviceName=vless-grpc&sni=${domain}#${user}"
systemctl restart xray
systemctl restart nginx
service cron restart
if [ ! -e /etc/vless ]; then
mkdir -p /etc/vless
fi
if [ -z ${Quota} ]; then
Quota="0"
fi
c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
d=$((${c} * 1024 * 1024 * 1024))
if [[ ${c} != "0" ]]; then
echo "${d} ${iplim}" >/etc/vless/${user}
fi
DATADB=$(cat /etc/vless/.vless.db | grep "^###" | grep -w "${user}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
sed -i "/${user}/d" /etc/vless/.vless.db
fi
echo "### ${user} ${exp}" >>/etc/vless/.vless.db
clear
echo -e "${g}┌────────────────────────┐${p}" | tee -a /etc/vless/${user}.log
echo -e "${b}    Xray/Vless Account     ${p}" | tee -a /etc/vless/${user}.log
echo -e "${g}└────────────────────────┘${p}" | tee -a /etc/vless/${user}.log
echo -e "Remarks      : ${user}" | tee -a /etc/vless/${user}.log
echo -e "Domain       : ${domain}" | tee -a /etc/vless/${user}.log
echo -e "Location     : $CITY" | tee -a /etc/vless/${user}.log
echo -e "User Quota   : ${Quota} GB" | tee -a /etc/vless/${user}.log
echo -e "Limit Adress : ${iplim} IP" | tee -a /etc/vless/${user}.log
echo -e "Port TLS     : 443" | tee -a /etc/vless/${user}.log
echo -e "Port NTLS    : 80" | tee -a /etc/vless/${user}.log
echo -e "Port GRPC    : 443" | tee -a /etc/vless/${user}.log
echo -e "User ID      : ${uuid}" | tee -a /etc/vless/${user}.log
echo -e "AlterId      : 0" | tee -a /etc/vless/${user}.log
echo -e "Security     : auto" | tee -a /etc/vless/${user}.log
echo -e "Network      : WS or gRPC" | tee -a /etc/vless/${user}.log
echo -e "Path         : (/vless) " | tee -a /etc/vless/${user}.log
echo -e "Path Dynamic : CF-XRAY:https://bug.com " | tee -a /etc/vless/${user}.log
echo -e "ServiceName  : vless-grpc" | tee -a /etc/vless/${user}.log
echo -e "${g}───────────────────────────${p}" | tee -a /etc/vless/${user}.log
echo -e "Link TLS     : ${vlesslink1}" | tee -a /etc/vless/${user}.log
echo -e "${g}───────────────────────────${p}" | tee -a /etc/vless/${user}.log
echo -e "Link NTLS    : ${vlesslink2}" | tee -a /etc/vless/${user}.log
echo -e "${g}───────────────────────────${p}" | tee -a /etc/vless/${user}.log
echo -e "Link GRPC    : ${vlesslink3}" | tee -a /etc/vless/${user}.log
echo -e "${g}───────────────────────────${p}" | tee -a /etc/vless/${user}.log
echo -e "Link Account : https://${domain}:81/vless-$user.txt" | tee -a /etc/vless/${user}.log
echo -e "${g}───────────────────────────${p}" | tee -a /etc/vless/${user}.log
echo -e "Expired On : $exp" | tee -a /etc/vless/${user}.log
echo -e "${g}───────────────────────────${p}" | tee -a /etc/vless/${user}.log
echo -e "" | tee -a /etc/vless/${user}.log
read -n 1 -s -r -p "Press [ Enter ] to back on menu"
vless
)
add_ws() (
clear
until [[ $user =~ ^[a-zA-Z0-9_]+$ && ${CLIENT_EXISTS} == '0' ]]; do
echo -e "${g}┌──────────────────────────────────────────┐${p}"
echo -e "${g}│${b}        Add Vless Ws Account         ${p}"
echo -e "${g}└──────────────────────────────────────────┘${p}"
read -p "Username : " user
CLIENT_EXISTS=$(grep -w $user /etc/xray/config.json | wc -l)
if [[ ${CLIENT_EXISTS} == '1' ]]; then
clear
echo -e "${g}┌──────────────────────────────────────────┐${p}"
echo ""
echo "      A client name was already created"
echo ""
echo -e "${g}└──────────────────────────────────────────┘${p}"
read -n 1 -s -r -p "Press [ Enter ] to back on menu"
menu
fi
done
uuid=$(cat /proc/sys/kernel/random/uuid)
read -p "Expired (days): " masaaktif
read -p "Limit Quota (GB): " Quota
read -p "Limit User (IP): " iplim
exp=$(date -d "$masaaktif days" +"%Y-%m-%d")
sed -i '/#vless$/a\#vl# '"$user $exp"'\
},{"id": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
cat >/var/www/html/vless-$user.txt <<-END
-----------------------------------------
UnderTunnel PROJECT
-----------------------------------------
Format Vless WS (TLS)
-----------------------------------------
- name: Vless-$user-WS (CDN)
server: ${domain}
port: 443
type: vless
uuid: ${uuid}
cipher: auto
tls: true
skip-cert-verify: true
servername: ${domain}
network: ws
ws-opts:
path: /vless
headers:
Host: ${domain}
udp: true
-----------------------------------------
Format Vless WS (NTLS)
-----------------------------------------
- name: Vless-$user
server: ${domain}
port: 80
type: vless
uuid: ${uuid}
cipher: auto
tls: false
skip-cert-verify: false
servername: ${domain}
network: ws
ws-opts:
path: /vless
headers:
Host: ${domain}
udp: true
-----------------------------------------
Link Vless Account
-----------------------------------------
Link TLS : vless://${uuid}@${domain}:443?path=/vless&security=tls&encryption=none&type=ws#${user}
-----------------------------------------
Link NTLS : vless://${uuid}@${domain}:80?path=/vless&encryption=none&type=ws#${user}
-----------------------------------------
END
vlesslink1="vless://${uuid}@${domain}:443?path=/vless&security=tls&encryption=none&type=ws#${user}"
vlesslink2="vless://${uuid}@${domain}:80?path=/vless&encryption=none&type=ws#${user}"
systemctl restart xray
systemctl restart nginx
service cron restart
if [ ! -e /etc/vless ]; then
mkdir -p /etc/vless
fi
if [ -z ${Quota} ]; then
Quota="0"
fi
c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
d=$((${c} * 1024 * 1024 * 1024))
if [[ ${c} != "0" ]]; then
echo "${d} ${iplim}" >/etc/vless/${user}
fi
DATADB=$(cat /etc/vless/.vless.db | grep "^###" | grep -w "${user}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
sed -i "/${user}/d" /etc/vless/.vless.db
fi
echo "### ${user} ${exp}" >>/etc/vless/.vless.db
clear
echo -e "${g}┌────────────────────────┐${p}" | tee -a /etc/vless/${user}.log
echo -e "${b}    Xray/Vless Account     ${p}" | tee -a /etc/vless/${user}.log
echo -e "${g}└────────────────────────┘${p}" | tee -a /etc/vless/${user}.log
echo -e "Remarks      : ${user}" | tee -a /etc/vless/${user}.log
echo -e "Domain       : ${domain}" | tee -a /etc/vless/${user}.log
echo -e "Location     : $CITY" | tee -a /etc/vless/${user}.log
echo -e "User Quota   : ${Quota} GB" | tee -a /etc/vless/${user}.log
echo -e "Limit Adress : ${iplim} IP" | tee -a /etc/vless/${user}.log
echo -e "Port TLS     : 443" | tee -a /etc/vless/${user}.log
echo -e "Port NTLS    : 80" | tee -a /etc/vless/${user}.log
echo -e "Port GRPC    : 443" | tee -a /etc/vless/${user}.log
echo -e "User ID      : ${uuid}" | tee -a /etc/vless/${user}.log
echo -e "AlterId      : 0" | tee -a /etc/vless/${user}.log
echo -e "Security     : auto" | tee -a /etc/vless/${user}.log
echo -e "Network      : WS or gRPC" | tee -a /etc/vless/${user}.log
echo -e "Path         : (/vless) " | tee -a /etc/vless/${user}.log
echo -e "Path Dynamic : CF-XRAY:https://bug.com " | tee -a /etc/vless/${user}.log
echo -e "ServiceName  : vless-grpc" | tee -a /etc/vless/${user}.log
echo -e "${g}───────────────────────────${p}" | tee -a /etc/vless/${user}.log
echo -e "Link TLS     : ${vlesslink1}" | tee -a /etc/vless/${user}.log
echo -e "${g}───────────────────────────${p}" | tee -a /etc/vless/${user}.log
echo -e "Link NTLS    : ${vlesslink2}" | tee -a /etc/vless/${user}.log
echo -e "${g}───────────────────────────${p}" | tee -a /etc/vless/${user}.log
echo -e "Link Account : https://${domain}:81/vless-$user.txt" | tee -a /etc/vless/${user}.log
echo -e "${g}───────────────────────────${p}" | tee -a /etc/vless/${user}.log
echo -e "Expired On : $exp" | tee -a /etc/vless/${user}.log
echo -e "${g}───────────────────────────${p}" | tee -a /etc/vless/${user}.log
echo -e "" | tee -a /etc/vless/${user}.log
read -n 1 -s -r -p "Press [ Enter ] to back on menu"
vless
)
add_grpc() (
clear
until [[ $user =~ ^[a-zA-Z0-9_]+$ && ${CLIENT_EXISTS} == '0' ]]; do
echo -e "${g}┌──────────────────────────────────────────┐${p}"
echo -e "${g}│${b}         Add Vless gRPC Account        ${p}"
echo -e "${g}└──────────────────────────────────────────┘${p}"
read -p "Username : " user
CLIENT_EXISTS=$(grep -w $user /etc/xray/config.json | wc -l)
if [[ ${CLIENT_EXISTS} == '1' ]]; then
clear
echo -e "${g}┌──────────────────────────────────────────┐${p}"
echo ""
echo "      A client name was already created"
echo ""
echo -e "${g}└──────────────────────────────────────────┘${p}"
read -n 1 -s -r -p "Press [ Enter ] to back on menu"
menu
fi
done
uuid=$(cat /proc/sys/kernel/random/uuid)
read -p "Expired (days): " masaaktif
read -p "Limit Quota (GB): " Quota
read -p "Limit User (IP): " iplim
exp=$(date -d "$masaaktif days" +"%Y-%m-%d")
sed -i '/#vlessgrpc$/a\#vl# '"$user $exp"'\
},{"id": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
cat >/var/www/html/vless-$user.txt <<-END
-----------------------------------------
UnderTunnel PROJECT
-----------------------------------------
Format Vless gRPC (SNI)
-----------------------------------------
- name: Vless-$user-gRPC (SNI)
server: ${domain}
port: 443
type: vless
uuid: ${uuid}
cipher: auto
tls: true
skip-cert-verify: true
servername: ${domain}
network: grpc
grpc-opts:
grpc-mode: gun
grpc-service-name: vless-grpc
udp: true
-----------------------------------------
Link Vless Account
-----------------------------------------
Link GRPC : vless://${uuid}@${domain}:443?mode=gun&security=tls&encryption=none&type=grpc&serviceName=vless-grpc&sni=${domain}#${user}
-----------------------------------------
END
vlesslink3="vless://${uuid}@${domain}:443?mode=gun&security=tls&encryption=none&type=grpc&serviceName=vless-grpc&sni=${domain}#${user}"
systemctl restart xray
systemctl restart nginx
service cron restart
if [ ! -e /etc/vless ]; then
mkdir -p /etc/vless
fi
if [ -z ${Quota} ]; then
Quota="0"
fi
c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
d=$((${c} * 1024 * 1024 * 1024))
if [[ ${c} != "0" ]]; then
echo "${d} ${iplim}" >/etc/vless/${user}
fi
DATADB=$(cat /etc/vless/.vless.db | grep "^###" | grep -w "${user}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
sed -i "/${user}/d" /etc/vless/.vless.db
fi
echo "### ${user} ${exp}" >>/etc/vless/.vless.db
clear
echo -e "${g}┌────────────────────────┐${p}" | tee -a /etc/vless/${user}.log
echo -e "${b}    Xray/Vless Account     ${p}" | tee -a /etc/vless/${user}.log
echo -e "${g}└────────────────────────┘${p}" | tee -a /etc/vless/${user}.log
echo -e "Remarks      : ${user}" | tee -a /etc/vless/${user}.log
echo -e "Domain       : ${domain}" | tee -a /etc/vless/${user}.log
echo -e "Location     : $CITY" | tee -a /etc/vless/${user}.log
echo -e "User Quota   : ${Quota} GB" | tee -a /etc/vless/${user}.log
echo -e "Limit Adress : ${iplim} IP" | tee -a /etc/vless/${user}.log
echo -e "Port TLS     : 443" | tee -a /etc/vless/${user}.log
echo -e "Port NTLS    : 80" | tee -a /etc/vless/${user}.log
echo -e "Port GRPC    : 443" | tee -a /etc/vless/${user}.log
echo -e "User ID      : ${uuid}" | tee -a /etc/vless/${user}.log
echo -e "AlterId      : 0" | tee -a /etc/vless/${user}.log
echo -e "Security     : auto" | tee -a /etc/vless/${user}.log
echo -e "Network      : WS or gRPC" | tee -a /etc/vless/${user}.log
echo -e "Path         : (/vless) " | tee -a /etc/vless/${user}.log
echo -e "Path Dynamic : CF-XRAY:https://bug.com " | tee -a /etc/vless/${user}.log
echo -e "ServiceName  : vless-grpc" | tee -a /etc/vless/${user}.log
echo -e "${g}───────────────────────────${p}" | tee -a /etc/vless/${user}.log
echo -e "Link GRPC    : ${vlesslink3}" | tee -a /etc/vless/${user}.log
echo -e "${g}───────────────────────────${p}" | tee -a /etc/vless/${user}.log
echo -e "Link Account : https://${domain}:81/vless-$user.txt" | tee -a /etc/vless/${user}.log
echo -e "${g}───────────────────────────${p}" | tee -a /etc/vless/${user}.log
echo -e "Expired On : $exp" | tee -a /etc/vless/${user}.log
echo -e "${g}───────────────────────────${p}" | tee -a /etc/vless/${user}.log
echo -e "" | tee -a /etc/vless/${user}.log
read -n 1 -s -r -p "Press [ Enter ] to back on menu"
vless
)
clear
grenbo="${gb}"
NC='${p}'
echo -e "${g}┌──────────────────────────────────────────┐${p}"
echo -e "${g}│${b}        ADD ACCOUNT VLESS              ${p}"
echo -e "${g}└──────────────────────────────────────────┘${p}"
echo -e "${g}┌──────────────────────────────────────────┐${p}"
echo -e "${g}│  ${gb}[1]•${b} Creating Vless ( All )${p}"
echo -e "${g}│  ${gb}[2]•${b} Creating Vless WS${p}"
echo -e "${g}│  ${gb}[3]•${b} Creating Vless gRPC${p}"
echo -e "${g}└──────────────────────────────────────────┘${p}"
echo -e ""
read -p "Select From Options [ 1 - 4 ] : " menu
case $menu in
1)
add_all
;;
2)
add_ws
;;
3)
add_grpc
;;
*)
echo -e "${Red}You wrong command !${Font}"
sleep 1
vless
;;
esac
