#!/bin/bash
g=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 2)
gb=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 3)
b=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 4)
p=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 5)
r=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 6)
y=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 7)
repo=https://raw.githubusercontent.com/gazzent/ip/main/ip
ipsaya=$(wget -qO- ipv4.icanhazip.com);
domain=$(cat /etc/xray/domain)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
useexp=$(wget -qO- ${repo} | grep $ipsaya | awk '{print $4}')
if [[ $date_list < $useexp ]]; then
echo -ne
else
echo -e "${g}────────────────────────────────────────────${p}"
echo -e "${b}          404 NOT FOUND AUTOSCRIPT          ${p}"
echo -e "${g}────────────────────────────────────────────${p}"
echo -e ""
echo -e "            ${r}PERMISSION DENIED OR!${p}"
echo -e "   ${y}Your VPS${p} $ipsaya ${y}Expired${p}"
echo -e "     ${y}Buy access permissions for scripts${p}"
echo -e "             ${y}Contact Admin :${p}"
echo -e "      ${gb}Telegram${p} t.me/candravpnz"
echo -e "${g}────────────────────────────────────────────${p}"
exit
fi
bot_ins() {
clear
pip3 install -r /root/.config/adminbot/xolpanel/requirements.txt
pip3 install pillow

clear
sleep 3

#input Data
echo ""
echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e " \e[1;97;101m          ADD BOT PANEL          \e[0m"
echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "${grenbo}Tutorial Creat Bot and ID Telegram${NC}"
echo -e "${grenbo}[*] Creat Bot and Token Bot : @BotFather${NC}"
echo -e "${grenbo}[*] Info Id Telegram : @MissRose_bot , perintah /id${NC}"
echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
read -e -p "[*] Input your Bot Token : " bottoken
read -e -p "[*] Input Your Id Telegram :" admin
echo -e BOT_TOKEN='"'$bottoken'"' >> /root/.config/xolpanel/var.txt
echo -e ADMIN='"'$admin'"' >> /root/.config/xolpanel/var.txt
echo -e DOMAIN='"'$domain'"' >> /root/.config/xolpanel/var.txt
systemctl start xolpanel
systemctl enable xolpanel
clear
sleep 2
fun_bar() {
        CMD[0]="$1"
        CMD[1]="$2"
        (
            [[ -e $HOME/fim ]] && rm $HOME/fim
            ${CMD[0]} -y >/dev/null 2>&1
            ${CMD[1]} -y >/dev/null 2>&1
            touch $HOME/fim
        ) >/dev/null 2>&1 &
        tput civis
        echo -ne "  \033[0;33mPlease Wait Loading \033[1;37m- \033[0;33m["
        while true; do
            for ((i = 0; i < 8; i++)); do
                echo -ne "🌐"
                sleep 0.1s
            done
            [[ -e $HOME/fim ]] && rm $HOME/fim && break
            echo -e "\033[0;33m]"
            sleep 1s
            tput cuu1
            tput dl1
            echo -ne "  \033[0;33mPlease Wait Loading \033[1;37m- \033[0;33m["
        done
        echo -e "\033[0;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
        tput cnorm
    }
    sssssss() {
        sleep 5
    }
    sssssssss() {
        sleep 5
    }
    ssssssssssss() {
        sleep 2
    }

    echo -e "  ${OR}──────────────────────────────────────${NC}"
    printf "\e[1;92m   .::.\e[0m\e[1;77mBOT SIMPLE MYVPN TELEGRAM \e[1;92m.::.\e[0m\n"
    echo -e "  ${OR}──────────────────────────────────────${NC}"
    echo -e ""
    echo -e "Setting up Telegram BOT"
    fun_bar 'sssssss'
    echo -e "Input Data API TOKEN"
    fun_bar 'sssssssss'
    echo -e "Input your ID"
    fun_bar 'ssssssssssss'
    echo -e ""
    echo -e ""
    clear
    BOTTSSSTT=$(systemctl status xolpanel | grep active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g')
    if [[ $BOTTSSSTT == "running" ]]; then
        BOTBOTTTTSUDADHTTT="${grenbo}🟢 Online${NC}"
    else
        BOTBOTTTTSUDADHTTT="${RED}🔴 Offline${NC}"
    fi
    echo -e "  ${OR}──────────────────────────────────────${NC}"
    echo -e "       YOUR 🤖BOT STATUS $BOTBOTTTTSUDADHTTT"
    echo -e "  ${OR}──────────────────────────────────────${NC}"
    echo -e "  You can start the bot with the command"
    echo -e "     (/menu Atau .menu) On your BOT"    
    echo -e ""
echo " Installations complete, type /menu on your bot"
echo ""
read -n 1 -s -r -p "Press any key to back on menu"
menu
}
bot_on() {
clear
systemctl start xolpanel
systemctl enable xolpanel
sleep 2
echo "Done"
echo "Your Data Bot"
read -n 1 -s -r -p "Press [ Enter ] to back on menu"
menu
}
bot_off() {
clear
systemctl stop xolpanel
systemctl disable xolpanel
sleep 2
echo "Done"
sleep 2
read -n 1 -s -r -p "Press [ Enter ] to back on menu"
menu
}
STS=$(systemctl status xolpanel | grep active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g')
if [[ $STS == "running" ]]; then
status="${b}🟢 Online${p}"
else
status="${r}🔴 Offline${p}"
fi
clear
echo -e " ${g}┌──────────────────────────────────────────┐${p}"
echo -e " ${b}            BOT PANEL TELEGRAM            ${p}"
echo -e " ${g}└──────────────────────────────────────────┘${p}"
echo -e " ${g}┌──────────────────────────────────────────┐${p}"
echo -e ""
echo -e "   ${gb}[1]•${b} Pasang Bot Telegram"
echo -e "   ${gb}[2]•${b} Start Bot Telegram"
echo -e "   ${gb}[3]•${b} Stop Bot Telegram"
echo -e ""
echo -e " ${g}└──────────────────────────────────────────┘${p}"
echo -e " ${g}┌──────────────────────────────────────────┐${p}"
echo -e "  ${gb} STATUS 🤖BOT${p} : $status"
echo -e " ${g}└──────────────────────────────────────────┘${p}"
echo -e ""
read -p "    Select From Options [ 1 - 3 ] : " OPT_MENU
echo -e ""
case $OPT_MENU in
1)
bot_ins
;;
2)
bot_on
;;
3)
bot_off
;;
*)
echo -e "${Red}You wrong command !${Font}"
sleep 1
menu
;;
esac
