#!/bin/bash
# Edition : Stable Edition V2.0
# Auther  : Muh Aripin Ilham
# (C) Copyright 2023-2024 By  Under Tunnel
# =========================================
#!/bin/bash
repo=https://raw.githubusercontent.com/gazzent/ip/main/ip
ipsaya=$(wget -qO- ipv4.icanhazip.com);
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
useexp=$(wget -qO- ${repo} | grep $ipsaya | awk '{print $4}')
if [[ $date_list < $useexp ]]; then
echo -ne
else
exit
fi
user="$2"
vm() (
exp=$(grep -E "$user" "/etc/vmess/.vmess.db" | cut -d ' ' -f 3 )
sed -i "/^#vm# $user $exp/,/^},{/d" /etc/xray/config.json
sed -i "/^### $user $exp/d" /etc/vmess/.vmess.db
rm /etc/vmess/$user.log >/dev/null
rm /etc/vmess/$user >/dev/null
rm /etc/vmess/cache/$user >/dev/null
rm /var/www/html/vmess-$user.txt >/dev/null
xray api stats --server=127.0.0.1:10000 -name "user>>>${user}>>>traffic>>>downlink" -reset > /dev/null 2>&1
systemctl daemon-reload >/dev/null 2>&1
systemctl restart xray >/dev/null 2>&1
)
vl() (
exp=$(grep -E "$user" "/etc/vless/.vless.db" | cut -d ' ' -f 3 )
sed -i "/^#vl# $user $exp/,/^},{/d" /etc/xray/config.json
sed -i "/^### $user $exp/d" /etc/vless/.vless.db
rm /etc/vless/$user.log >/dev/null
rm /etc/vless/$user >/dev/null
rm /etc/vless/cache/$user >/dev/null
rm /var/www/html/vless-$user.txt >/dev/null
xray api stats --server=127.0.0.1:10000 -name "user>>>${user}>>>traffic>>>downlink" -reset > /dev/null 2>&1
systemctl daemon-reload >/dev/null 2>&1
systemctl restart xray >/dev/null 2>&1
)
tr() (
exp=$(grep -E "$user" "/etc/trojan/.trojan.db" | cut -d ' ' -f 3 )
sed -i "/^#tr# $user $exp/,/^},{/d" /etc/xray/config.json
sed -i "/^### $user $exp/d" /etc/trojan/.trojan.db
rm /etc/trojan/$user.log >/dev/null
rm /etc/trojan/$user >/dev/null
rm /etc/trojan/cache/$user >/dev/null
rm /var/www/html/trojan-$user.txt >/dev/null
xray api stats --server=127.0.0.1:10000 -name "user>>>${user}>>>traffic>>>downlink" -reset > /dev/null 2>&1
systemctl daemon-reload >/dev/null 2>&1
systemctl restart xray >/dev/null 2>&1
)
ss() (
exp=$(grep -E "$user" "/etc/shadowsocks/.shadowsocks.db" | cut -d ' ' -f 3 )
sed -i "/^#ss# $user $exp/,/^},{/d" /etc/xray/config.json
sed -i "/^### $user $exp/d" /etc/shadowsocks/.shadowsocks.db
rm /etc/shadowsocks/$user.log >/dev/null
rm /etc/shadowsocks/$user >/dev/null
rm /etc/shadowsocks/cache/$user >/dev/null
rm /var/www/html/ss-$user.txt >/dev/null
xray api stats --server=127.0.0.1:10000 -name "user>>>${user}>>>traffic>>>downlink" -reset > /dev/null 2>&1
systemctl daemon-reload >/dev/null 2>&1
systemctl restart xray >/dev/null 2>&1
)
sssh() (
exp=$(grep -E "$user" "/etc/ssh/.ssh.db" | cut -d ' ' -f 3 )
getent passwd ${user}  >/dev/null 2>&1
userdel --force $user
sed -i "/^### $user $exp/d" /etc/ssh/.ssh.db
rm /etc/ssh/$user.log >/dev/null
rm /etc/ssh/$user >/dev/null
rm /var/www/html/ssh-$user.txt >/dev/null
systemctl daemon-reload >/dev/null 2>&1
systemctl restart ssh >/dev/null 2>&1
systemctl restart sshd >/dev/null 2>&1
systemctl restart dropbear >/dev/null 2>&1
)
if [[ ${1} == "vmess" ]]; then
vm
fi
if [[ ${1} == "vless" ]]; then
vl
fi
if [[ ${1} == "trojan" ]]; then
tr
fi
if [[ ${1} == "ssh" ]]; then
sssh
fi
if [[ ${1} == "ss" ]]; then
ss
fi
