#!/bin/bash
# Edition : Stable Edition V2.0
# Auther  : Muh Aripin Ilham
# (C) Copyright 2023-2024 By  Under Tunnel
# =========================================
#!/bin/bash
g=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 2)
gb=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 3)
b=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 4)
p=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 5)
r=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 6)
y=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 7)
MYIP=$(wget -qO- ipv4.icanhazip.com);
repo=https://raw.githubusercontent.com/gazzent/ip/main/ip
ipsaya=$(wget -qO- ipv4.icanhazip.com);
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
useexp=$(wget -qO- ${repo} | grep $ipsaya | awk '{print $4}')
if [[ $date_list < $useexp ]]; then
echo -ne
else
echo -e "${g}────────────────────────────────────────────${p}"
echo -e "${b}          404 NOT FOUND AUTOSCRIPT          ${p}"
echo -e "${g}────────────────────────────────────────────${p}"
echo -e ""
echo -e "            ${r}PERMISSION DENIED OR!${p}"
echo -e "   ${y}Your VPS${p} $ipsaya ${y}Expired${p}"
echo -e "     ${y}Buy access permissions for scripts${p}"
echo -e "             ${y}Contact Admin :${p}"
echo -e "      ${gb}Telegram${p} t.me/mehonk_mt"
echo -e "${g}────────────────────────────────────────────${p}"
exit
fi
triall_exp(){
echo -e "${g}┌──────────────────────────────────────────┐${p}"
echo -e ""
echo -e "      ${gb}[1]•${b} Triall 15 Minutes"
echo -e "      ${gb}[2]•${b} Triall 30 Minutes"
echo -e "      ${gb}[3]•${b} Triall 1 Jam/Hours"
echo -e ""
echo -e "${g}└──────────────────────────────────────────┘${p}"
echo -e ""
read -p "       Select From Options [ 1 - 3 ] : " OPT_MENU
echo -e ""
case $OPT_MENU in
1)
jamm="15 minutes"
;;
2)
jamm="30 minutes"
;;
3)
jamm="1 hours"
;;
*)
echo -e "${Red}You wrong command !${Font}"
sleep 1
menu
;;
esac
}
echo "Loading..."
red() { echo -e "\033[32;1m${*}\${p}"; }
domain=$(cat /etc/xray/domain)
PUB=$(cat /etc/slowdns/server.pub)
CITY=$(cat /etc/xray/city)
NS=$(cat /etc/xray/dns)
clear
add_all() (
clear
echo -e "${g}┌──────────────────────────────────────────┐${p}"
echo -e "${g}│${b}         Add Trojan Ws & gRPC Account           ${p}"
echo -e "${g}└──────────────────────────────────────────┘${p}"
triall_exp
uuid=$(cat /proc/sys/kernel/random/uuid)
masaaktif=1
Quota=1
user=Trial-TR`</dev/urandom tr -dc 0-9 | head -c3`
CLIENT_EXISTS=$(grep -w $user /etc/trojan/.trojan.db | wc -l)
if [[ ${CLIENT_EXISTS} == '1' ]]; then
exit
clear
echo -e "${g}┌──────────────────────────────────────────┐${p}"
echo ""
echo "      A client name was already created"
echo ""
echo -e "${g}└──────────────────────────────────────────┘${p}"
read -n 1 -s -r -p "Press [ Enter ] to back on menu"
trojan
fi
exp=$(date -d "$masaaktif days" +"%Y-%m-%d")
read -p "Limit User (IP): " iplim
sed -i '/#trojanws$/a\#tr# '"$user $exp"'\
},{"password": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
sed -i '/#trojangrpc$/a\#tr# '"$user $exp"'\
},{"password": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
trojanlink1="trojan://${uuid}@${domain}:443?path=%2Ftrojan&security=tls&host=${domain}&type=ws&sni=${domain}#${user}"
trojanlink2="trojan://${uuid}@${domain}:80?path=%2Ftrojan&security=none&host=${domain}&type=ws&sni=${domain}#${user}"
trojanlink3="trojan://${uuid}@${domain}:443?mode=gun&security=tls&type=grpc&serviceName=trojan-grpc&sni=${domain}#${user}"
cat >/var/www/html/trojan-$user.txt <<-END
-----------------------------------------
UnderTunnel PROJECT
-----------------------------------------
Format Trojan WS (TLS)
-----------------------------------------
- name: Trojan-$user
server: ${domain}
port: 443
type: trojan
password: ${uuid}
network: ws
sni: ${domain}
skip-cert-verify: true
udp: true
ws-opts:
path: /trojan
headers:
Host: ${domain}
-----------------------------------------
Format Trojan WS (NTLS)
-----------------------------------------
- name: Trojan-$user
server: ${domain}
port: 80
type: trojan
password: ${uuid}
network: ws
sni: ${domain}
tls: false
skip-cert-verify: true
udp: true
ws-opts:
path: /trojan
headers:
Host: ${domain}
-----------------------------------------
Format Trojan gRPC (SNI)
-----------------------------------------
- name: Trojan-$user
type: trojan
server: ${domain}
port: 443
password: ${uuid}
udp: true
sni: ${domain}
skip-cert-verify: true
network: grpc
grpc-opts:
grpc-service-name: trojan-grpc
-----------------------------------------
Link Trojan Account
-----------------------------------------
Link TLS : trojan://${uuid}@${domain}:443?path=%2Ftrojan&security=tls&host=${domain}&type=ws&sni=${domain}#${user}
-----------------------------------------
Link NTLS : trojan://${uuid}@${domain}:80?path=%2Ftrojan&security=none&host=${domain}&type=ws&sni=${domain}#${user}
-----------------------------------------
Link gRPC : trojan://${uuid}@${domain}:443?mode=gun&security=tls&type=grpc&serviceName=trojan-grpc&sni=${domain}#${user}
-----------------------------------------
END
systemctl restart xray
systemctl restart nginx
service cron restart
if [ ! -e /etc/trojan ]; then
mkdir -p /etc/trojan
fi
if [ -z ${Quota} ]; then
Quota="0"
fi
c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
d=$((${c} * 1024 * 1024 * 1024))
if [[ ${c} != "0" ]]; then
echo "${d} ${iplim}" >/etc/trojan/${user}
fi
DATADB=$(cat /etc/trojan/.trojan.db | grep "^###" | grep -w "${user}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
sed -i "/${user}/d" /etc/trojan/.trojan.db
fi
echo "### ${user} ${exp}" >>/etc/trojan/.trojan.db
clear
echo -e "${g}┌────────────────────────┐${p}" | tee -a /etc/trojan/${user}.log
echo -e "${b}    Xray/Trojan Account     ${p}" | tee -a /etc/trojan/${user}.log
echo -e "${g}└────────────────────────┘${p}" | tee -a /etc/trojan/${user}.log
echo -e "Remarks      : ${user}" | tee -a /etc/trojan/${user}.log
echo -e "Domain       : ${domain}" | tee -a /etc/trojan/${user}.log
echo -e "Location     : $CITY" | tee -a /etc/trojan/${user}.log
echo -e "User Quota   : ${Quota} GB" | tee -a /etc/trojan/${user}.log
echo -e "Limit Adress : ${iplim} IP" | tee -a /etc/trojan/${user}.log
echo -e "Port TLS     : 443" | tee -a /etc/trojan/${user}.log
echo -e "Port NTLS    : 80" | tee -a /etc/trojan/${user}.log
echo -e "Port GRPC    : 443" | tee -a /etc/trojan/${user}.log
echo -e "User ID      : ${uuid}" | tee -a /etc/trojan/${user}.log
echo -e "AlterId      : 0" | tee -a /etc/trojan/${user}.log
echo -e "Security     : auto" | tee -a /etc/trojan/${user}.log
echo -e "Network      : WS or gRPC" | tee -a /etc/trojan/${user}.log
echo -e "Path         : (/trojan) " | tee -a /etc/trojan/${user}.log
echo -e "Path Dynamic : CF-XRAY:https://bug.com " | tee -a /etc/trojan/${user}.log
echo -e "ServiceName  : trojan-grpc" | tee -a /etc/trojan/${user}.log
echo -e "${g}───────────────────────────${p}" | tee -a /etc/trojan/${user}.log
echo -e "Link TLS     : ${trojanlink1}" | tee -a /etc/trojan/${user}.log
echo -e "${g}───────────────────────────${p}" | tee -a /etc/trojan/${user}.log
echo -e "Link NTLS    : ${trojanlink2}" | tee -a /etc/trojan/${user}.log
echo -e "${g}───────────────────────────${p}" | tee -a /etc/trojan/${user}.log
echo -e "Link GRPC    : ${trojanlink3}" | tee -a /etc/trojan/${user}.log
echo -e "${g}───────────────────────────${p}" | tee -a /etc/trojan/${user}.log
echo -e "Link Account : https://${domain}:81/trojan-$user.txt" | tee -a /etc/trojan/${user}.log
echo -e "${g}───────────────────────────${p}" | tee -a /etc/trojan/${user}.log
echo -e "Expired On : $jamm" | tee -a /etc/trojan/${user}.log
echo -e "${g}───────────────────────────${p}" | tee -a /etc/trojan/${user}.log
echo -e "" | tee -a /etc/trojan/${user}.log
echo "ktriall trojan ${user}" | at now +$jamm >/dev/null 2>&1
read -n 1 -s -r -p "Press [ Enter ] to back on menu"
trojan
)
add_ws() (
clear
echo -e "${g}┌──────────────────────────────────────────┐${p}"
echo -e "${g}│${b}         Add Trojan Ws Account           ${p}"
echo -e "${g}└──────────────────────────────────────────┘${p}"
triall_exp
uuid=$(cat /proc/sys/kernel/random/uuid)
masaaktif=1
Quota=5
user=Trial-TR`</dev/urandom tr -dc 0-9 | head -c3`
CLIENT_EXISTS=$(grep -w $user /etc/trojan/.trojan.db | wc -l)
if [[ ${CLIENT_EXISTS} == '1' ]]; then
exit
clear
echo -e "${g}┌──────────────────────────────────────────┐${p}"
echo ""
echo "      A client name was already created"
echo ""
echo -e "${g}└──────────────────────────────────────────┘${p}"
read -n 1 -s -r -p "Press [ Enter ] to back on menu"
trojan
fi
exp=$(date -d "$masaaktif days" +"%Y-%m-%d")
read -p "Limit User (IP): " iplim
sed -i '/#trojanws$/a\#tr# '"$user $exp"'\
},{"password": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
trojanlink1="trojan://${uuid}@${domain}:443?path=%2Ftrojan&security=tls&host=${domain}&type=ws&sni=${domain}#${user}"
trojanlink2="trojan://${uuid}@${domain}:80?path=%2Ftrojan&security=none&host=${domain}&type=ws&sni=${domain}#${user}"
cat >/var/www/html/trojan-$user.txt <<-END
-----------------------------------------
UnderTunnel PROJECT
-----------------------------------------
Format Trojan WS (TLS)
-----------------------------------------
- name: Trojan-$user
server: ${domain}
port: 443
type: trojan
password: ${uuid}
network: ws
sni: ${domain}
skip-cert-verify: true
udp: true
ws-opts:
path: /trojan
headers:
Host: ${domain}
-----------------------------------------
Format Trojan WS (NTLS)
-----------------------------------------
- name: Trojan-$user
server: ${domain}
port: 80
type: trojan
password: ${uuid}
network: ws
sni: ${domain}
tls: false
skip-cert-verify: true
udp: true
ws-opts:
path: /trojan
headers:
Host: ${domain}
-----------------------------------------
Link Trojan Account
-----------------------------------------
Link TLS : trojan://${uuid}@${domain}:443?path=%2Ftrojan&security=tls&host=${domain}&type=ws&sni=${domain}#${user}
-----------------------------------------
Link NTLS : trojan://${uuid}@${domain}:80?path=%2Ftrojan&security=none&host=${domain}&type=ws&sni=${domain}#${user}
-----------------------------------------
END
systemctl restart xray
systemctl restart nginx
service cron restart
if [ ! -e /etc/trojan ]; then
mkdir -p /etc/trojan
fi
if [ -z ${Quota} ]; then
Quota="0"
fi
c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
d=$((${c} * 1024 * 1024 * 1024))
if [[ ${c} != "0" ]]; then
echo "${d} ${iplim}" >/etc/trojan/${user}
fi
DATADB=$(cat /etc/trojan/.trojan.db | grep "^###" | grep -w "${user}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
sed -i "/${user}/d" /etc/trojan/.trojan.db
fi
echo "### ${user} ${exp}" >>/etc/trojan/.trojan.db
clear
echo -e "${g}┌────────────────────────┐${p}" | tee -a /etc/trojan/${user}.log
echo -e "${b}    Xray/Trojan Account     ${p}" | tee -a /etc/trojan/${user}.log
echo -e "${g}└────────────────────────┘${p}" | tee -a /etc/trojan/${user}.log
echo -e "Remarks      : ${user}" | tee -a /etc/trojan/${user}.log
echo -e "Domain       : ${domain}" | tee -a /etc/trojan/${user}.log
echo -e "Location     : $CITY" | tee -a /etc/trojan/${user}.log
echo -e "User Quota   : ${Quota} GB" | tee -a /etc/trojan/${user}.log
echo -e "Limit Adress : ${iplim} IP" | tee -a /etc/trojan/${user}.log
echo -e "Port TLS     : 443" | tee -a /etc/trojan/${user}.log
echo -e "Port NTLS    : 80" | tee -a /etc/trojan/${user}.log
echo -e "Port GRPC    : 443" | tee -a /etc/trojan/${user}.log
echo -e "User ID      : ${uuid}" | tee -a /etc/trojan/${user}.log
echo -e "AlterId      : 0" | tee -a /etc/trojan/${user}.log
echo -e "Security     : auto" | tee -a /etc/trojan/${user}.log
echo -e "Network      : WS or gRPC" | tee -a /etc/trojan/${user}.log
echo -e "Path         : (/trojan) " | tee -a /etc/trojan/${user}.log
echo -e "Path Dynamic : CF-XRAY:https://bug.com " | tee -a /etc/trojan/${user}.log
echo -e "ServiceName  : trojan-grpc" | tee -a /etc/trojan/${user}.log
echo -e "${g}───────────────────────────${p}" | tee -a /etc/trojan/${user}.log
echo -e "Link TLS     : ${trojanlink1}" | tee -a /etc/trojan/${user}.log
echo -e "${g}───────────────────────────${p}" | tee -a /etc/trojan/${user}.log
echo -e "Link NTLS    : ${trojanlink2}" | tee -a /etc/trojan/${user}.log
echo -e "${g}───────────────────────────${p}" | tee -a /etc/trojan/${user}.log
echo -e "Link Account : https://${domain}:81/trojan-$user.txt" | tee -a /etc/trojan/${user}.log
echo -e "${g}───────────────────────────${p}" | tee -a /etc/trojan/${user}.log
echo -e "Expired On : $jamm" | tee -a /etc/trojan/${user}.log
echo -e "${g}───────────────────────────${p}" | tee -a /etc/trojan/${user}.log
echo -e "" | tee -a /etc/trojan/${user}.log
echo "ktriall trojan ${user}" | at now +$jamm >/dev/null 2>&1
read -n 1 -s -r -p "Press [ Enter ] to back on menu"
trojan
)
add_grpc() (
clear
echo -e "${g}┌──────────────────────────────────────────┐${p}"
echo -e "${g}│${b}         Add Trojan Ws & gRPC Account           ${p}"
echo -e "${g}└──────────────────────────────────────────┘${p}"
triall_exp
uuid=$(cat /proc/sys/kernel/random/uuid)
masaaktif=1
Quota=5
user=Trial-TR`</dev/urandom tr -dc 0-9 | head -c3`
CLIENT_EXISTS=$(grep -w $user /etc/trojan/.trojan.db | wc -l)
if [[ ${CLIENT_EXISTS} == '1' ]]; then
exit
clear
echo -e "${g}┌──────────────────────────────────────────┐${p}"
echo ""
echo "      A client name was already created"
echo ""
echo -e "${g}└──────────────────────────────────────────┘${p}"
read -n 1 -s -r -p "Press [ Enter ] to back on menu"
trojan
fi
exp=$(date -d "$masaaktif days" +"%Y-%m-%d")
read -p "Limit User (IP): " iplim
sed -i '/#trojangrpc$/a\#tr# '"$user $exp"'\
},{"password": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
trojanlink3="trojan://${uuid}@${domain}:443?mode=gun&security=tls&type=grpc&serviceName=trojan-grpc&sni=${domain}#${user}"
cat >/var/www/html/trojan-$user.txt <<-END
-----------------------------------------
UnderTunnel PROJECT
-----------------------------------------
Format Trojan gRPC (SNI)
-----------------------------------------
- name: Trojan-$user
type: trojan
server: ${domain}
port: 443
password: ${uuid}
udp: true
sni: ${domain}
skip-cert-verify: true
network: grpc
grpc-opts:
grpc-service-name: trojan-grpc
-----------------------------------------
Link Trojan Account
-----------------------------------------
Link gRPC : trojan://${uuid}@${domain}:443?mode=gun&security=tls&type=grpc&serviceName=trojan-grpc&sni=${domain}#${user}
-----------------------------------------
END
systemctl restart xray
systemctl restart nginx
service cron restart
if [ ! -e /etc/trojan ]; then
mkdir -p /etc/trojan
fi
if [ -z ${Quota} ]; then
Quota="0"
fi
c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
d=$((${c} * 1024 * 1024 * 1024))
if [[ ${c} != "0" ]]; then
echo "${d} ${iplim}" >/etc/trojan/${user}
fi
DATADB=$(cat /etc/trojan/.trojan.db | grep "^###" | grep -w "${user}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
sed -i "/${user}/d" /etc/trojan/.trojan.db
fi
echo "### ${user} ${exp}" >>/etc/trojan/.trojan.db
clear
echo -e "${g}┌────────────────────────┐${p}" | tee -a /etc/trojan/${user}.log
echo -e "${b}    Xray/Trojan Account     ${p}" | tee -a /etc/trojan/${user}.log
echo -e "${g}└────────────────────────┘${p}" | tee -a /etc/trojan/${user}.log
echo -e "Remarks      : ${user}" | tee -a /etc/trojan/${user}.log
echo -e "Domain       : ${domain}" | tee -a /etc/trojan/${user}.log
echo -e "Location     : $CITY" | tee -a /etc/trojan/${user}.log
echo -e "User Quota   : ${Quota} GB" | tee -a /etc/trojan/${user}.log
echo -e "Limit Adress : ${iplim} IP" | tee -a /etc/trojan/${user}.log
echo -e "Port TLS     : 443" | tee -a /etc/trojan/${user}.log
echo -e "Port NTLS    : 80" | tee -a /etc/trojan/${user}.log
echo -e "Port GRPC    : 443" | tee -a /etc/trojan/${user}.log
echo -e "User ID      : ${uuid}" | tee -a /etc/trojan/${user}.log
echo -e "AlterId      : 0" | tee -a /etc/trojan/${user}.log
echo -e "Security     : auto" | tee -a /etc/trojan/${user}.log
echo -e "Network      : WS or gRPC" | tee -a /etc/trojan/${user}.log
echo -e "Path         : (/trojan) " | tee -a /etc/trojan/${user}.log
echo -e "Path Dynamic : CF-XRAY:https://bug.com " | tee -a /etc/trojan/${user}.log
echo -e "ServiceName  : trojan-grpc" | tee -a /etc/trojan/${user}.log
echo -e "${g}───────────────────────────${p}" | tee -a /etc/trojan/${user}.log
echo -e "Link GRPC    : ${trojanlink3}" | tee -a /etc/trojan/${user}.log
echo -e "${g}───────────────────────────${p}" | tee -a /etc/trojan/${user}.log
echo -e "Link Account : https://${domain}:81/trojan-$user.txt" | tee -a /etc/trojan/${user}.log
echo -e "${g}───────────────────────────${p}" | tee -a /etc/trojan/${user}.log
echo -e "Expired On : $jamm" | tee -a /etc/trojan/${user}.log
echo -e "${g}───────────────────────────${p}" | tee -a /etc/trojan/${user}.log
echo -e "" | tee -a /etc/trojan/${user}.log
echo "ktriall trojan ${user}" | at now +$jamm >/dev/null 2>&1
read -n 1 -s -r -p "Press [ Enter ] to back on menu"
trojan
)
clear
grenbo="${gb}"
NC='${p}'
echo -e "${g}┌──────────────────────────────────────────┐${p}"
echo -e "${g}│${b}      TRIALL ACCOUNT TROJAN              ${p}"
echo -e "${g}└──────────────────────────────────────────┘${p}"
echo -e "${g}┌──────────────────────────────────────────┐${p}"
echo -e "${g}│  ${gb}[1]•${b} Creating Trojan ( All )${p}"
echo -e "${g}│  ${gb}[2]•${b} Creating Trojan WS${p}"
echo -e "${g}│  ${gb}[3]•${b} Creating Trojan gRPC${p}"
echo -e "${g}└──────────────────────────────────────────┘${p}"
echo -e ""
read -p "Select From Options [ 1 - 3 ] : " menu
case $menu in
1)
add_all
;;
2)
add_ws
;;
3)
add_grpc
;;
*)
echo -e "${Red}You wrong command !${Font}"
sleep 1
trojan
;;
esac
