#!/bin/bash
# Edition : Stable Edition V2.0
# Auther  : Muh Aripin Ilham
# (C) Copyright 2023-2024 By  Under Tunnel
# =========================================
#!/bin/bash
g=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 2)
gb=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 3)
b=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 4)
p=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 5)
r=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 6)
y=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 7)
MYIP=$(wget -qO- ipv4.icanhazip.com);
repo=https://raw.githubusercontent.com/gazzent/ip/main/ip
ipsaya=$(wget -qO- ipv4.icanhazip.com);
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
useexp=$(wget -qO- ${repo} | grep $ipsaya | awk '{print $4}')
if [[ $date_list < $useexp ]]; then
echo -ne
else
echo -e "${g}────────────────────────────────────────────${p}"
echo -e "${b}          404 NOT FOUND AUTOSCRIPT          ${p}"
echo -e "${g}────────────────────────────────────────────${p}"
echo -e ""
echo -e "            ${r}PERMISSION DENIED OR!${p}"
echo -e "   ${y}Your VPS${p} $ipsaya ${y}Expired${p}"
echo -e "     ${y}Buy access permissions for scripts${p}"
echo -e "             ${y}Contact Admin :${p}"
echo -e "      ${gb}Telegram${p} t.me/mehonk_mt"
echo -e "${g}────────────────────────────────────────────${p}"
exit
fi
echo "Loading..."
clear
red() { echo -e "\033[32;1m${*}\${p}"; }
IP=$(curl -sS ifconfig.me)
domain=$(cat /etc/xray/domain)
PUB=$(cat /etc/slowdns/server.pub)
CITY=$(cat /etc/xray/city)
NS=$(cat /etc/xray/dns)
clear
echo -e "${g}┌──────────────────────────────────────────┐${p}"
echo -e "${g}│${b}         Add SSH OpenVPN Account           ${p}"
echo -e "${g}└──────────────────────────────────────────┘${p}"
user=Trial-SSH`</dev/urandom tr -dc 0-9 | head -c3`
CLIENT_EXISTS=$(grep -w $user /etc/ssh/.ssh.db | wc -l)
if [[ ${CLIENT_EXISTS} == '1' ]]; then
exit
clear
echo -e "${g}┌──────────────────────────────────────────┐${p}"
echo ""
echo "      A client name was already created"
echo ""
echo -e "${g}└──────────────────────────────────────────┘${p}"
read -n 1 -s -r -p "Press [ Enter ] to back on menu"
ssh
fi
echo -e "${g}┌──────────────────────────────────────────┐${p}"
echo -e ""
echo -e "      ${gb}[1]•${b} Triall 15 Minutes"
echo -e "      ${gb}[2]•${b} Triall 30 Minutes"
echo -e "      ${gb}[3]•${b} Triall 1 Jam/Hours"
echo -e ""
echo -e "${g}└──────────────────────────────────────────┘${p}"
echo -e ""
read -p "       Select From Options [ 1 - 3 ] : " OPT_MENU
echo -e ""
case $OPT_MENU in
1)
jamm="15 minutes"
;;
2)
jamm="30 minutes"
;;
3)
jamm="1 hours"
;;
*)
echo -e "${Red}You wrong command !${Font}"
sleep 1
menu
;;
esac
PASSWD=PW-`</dev/urandom tr -dc 0-9 | head -c4`
EXPIRED=1
expr=$(date -d "$EXPIRED days" +"%Y-%m-%d")
read -p "Limit User (IP): " iplim
useradd -e `date -d "$EXPIRED days" +"%Y-%m-%d"` -s /bin/false -M $user
exp="$(chage -l $user | grep "Account expires" | awk -F": " '{print $2}')"
echo -e "$PASSWD
$PASSWD
"|passwd $user &> /dev/null
echo "${iplim}" >/etc/ssh/${user}
DATADB=$(cat /etc/ssh/.ssh.db | grep "^###" | grep -w "${user}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
sed -i "/${user}/d" /etc/ssh/.ssh.db
fi
echo "### ${user} ${expr} " >>/etc/ssh/.ssh.db
cat > /var/www/html/ssh-$user.txt <<-END
-----------------------------------------
UnderTunnel PROJECT
-----------------------------------------
>> Format SSH OVPN Account <<
-----------------------------------------
Username         : $user
Password         : $PASSWD
Expired          : $jamm
-----------------------------------------
>> Detail Port <<
-----------------------------------------
Limit Adress     : ${iplim} IP
Host Domain      : $domain
Host NSDomaim    : ${NS}
Pub Key          : ${PUB}
Location         : $CITY
OpenSSH          : 22
Dropbear         : 143, 109
SlowDNS          : 443, 53, 88
SSH UDP          : 54-65535
WSS NTLS         : 80, 8080, 8880
WSS TLS/SNI      : 443
SSL TLS/SNI      : 443
OVPN WS/SSL      : 443
OVPN TCP         : 1194
OVPN UDP         : 2200
Proxy Squid 1    : 3128
BadVPN UDP       : 7100, 7200, 7300
-----------------------------------------
Payload HTTP : GET / HTTP/1.1[crlf]Host: $domain[crlf]Upgrade: websocket[crlf][crlf]
-----------------------------------------
Payload WSS : GET wss://BUG.COM/ HTTP/1.1[crlf]Host: $domain[crlf]Upgrade: websocket[crlf][crlf]
-----------------------------------------
Config OpenVPN : https://$domain:81/OpenVPN.zip
Config Psiphon : https://$domain:81/psiphon.txt
-----------------------------------------
-----------------------------------------
>> Detail Account SSH & UDP <<
-----------------------------------------
SSH  : $domain:80@$user:$PASSWD
UDP1 : $domain:54-65535@$user:$PASSWD
UDP2 : $domain:7100-7300@$user:$PASSWD
-----------------------------------------
END
clear
echo -e "${g}┌────────────────────────┐${p}" | tee -a /etc/ssh/${user}.log
echo -e "${b}      SSH OVPN Account   ${p}" | tee -a /etc/ssh/${user}.log
echo -e "${g}└────────────────────────┘${p}" | tee -a /etc/ssh/${user}.log
echo -e "Username        : $user" | tee -a /etc/ssh/${user}.log
echo -e "Password        : $PASSWD" | tee -a /etc/ssh/${user}.log
echo -e "Expired         : $jamm" | tee -a /etc/ssh/${user}.log
echo -e "${g}─────────────────────────${p}" | tee -a /etc/ssh/${user}.log
echo -e "Host Domain     : $domain" | tee -a /etc/ssh/${user}.log
echo -e "Host NSDomaim   : ${NS}" | tee -a /etc/ssh/${user}.log
echo -e "Pub Key         : ${PUB}" | tee -a /etc/ssh/${user}.log
echo -e "Location        : $CITY" | tee -a /etc/ssh/${user}.log
echo -e "${g}─────────────────────────${p}" | tee -a /etc/ssh/${user}.log
echo -e "Limit Adress    : ${iplim} IP" | tee -a /etc/ssh/${user}.log
echo -e "OpenSSH         : 22" | tee -a /etc/ssh/${user}.log
echo -e "SlowDNS         : 443, 53 ,88" | tee -a /etc/ssh/${user}.log
echo -e "SSH UDP         : 54-65535" | tee -a /etc/ssh/${user}.log
echo -e "WSS Dropbear    : 143, 109" | tee -a /etc/ssh/${user}.log
echo -e "WSS NTLS        : 80, 8080, 8880" | tee -a /etc/ssh/${user}.log
echo -e "WSS TLS/SNI     : 443" | tee -a /etc/ssh/${user}.log
echo -e "SSL TLS/SNI     : 443" | tee -a /etc/ssh/${user}.log
echo -e "OpenVPN         : 1194, 2200, 443" | tee -a /etc/ssh/${user}.log
echo -e "Proxy Squid     : 3128" | tee -a /etc/ssh/${user}.log
echo -e "BadVPN UDP      : 7100, 7200, 7300" | tee -a /etc/ssh/${user}.log
echo -e "${g}─────────────────────────${p}" | tee -a /etc/ssh/${user}.log
echo -e "Payload HTTP    : GET / HTTP/1.1[crlf]Host: $domain[crlf]Upgrade: websocket[crlf][crlf]" | tee -a /etc/ssh/${user}.log
echo -e "${g}─────────────────────────${p}" | tee -a /etc/ssh/${user}.log
echo -e "Payload WSS     : GET wss://BUG.COM/ HTTP/1.1[crlf]Host: $domain[crlf]Upgrade: websocket[crlf][crlf]" | tee -a /etc/ssh/${user}.log
echo -e "${g}─────────────────────────${p}" | tee -a /etc/ssh/${user}.log
echo -e "Config OpenVPN  : https://$domain:81/OpenVPN.zip" | tee -a /etc/ssh/${user}.log
echo -e "Config Psiphon  : https://$domain:81/psiphon.txt" | tee -a /etc/ssh/${user}.log
echo -e "${g}─────────────────────────${p}" | tee -a /etc/ssh/${user}.log
echo -e "${b}        Detail Account     ${p}" | tee -a /etc/ssh/${user}.log
echo -e "${g}─────────────────────────${p}" | tee -a /etc/ssh/${user}.log
echo -e "SSH   : $domain:80@$user:$PASSWD" | tee -a /etc/ssh/${user}.log
echo -e "UDP1  : $domain:54-65535@$user:$PASSWD" | tee -a /etc/ssh/${user}.log
echo -e "UDP2  : $domain:7100-7300@$user:$PASSWD" | tee -a /etc/ssh/${user}.log
echo -e "${g}─────────────────────────${p}" | tee -a /etc/ssh/${user}.log
echo -e "Link Account    : https://$domain:81/ssh-$user.txt"
echo -e "${g}─────────────────────────${p}" | tee -a /etc/ssh/${user}.log
echo -e "" | tee -a /etc/ssh/${user}.log
echo "ktriall ssh ${user}" | at now +$jamm >/dev/null 2>&1
read -n 1 -s -r -p "Press [ Enter ] to back on menu"
ssh
