#!/bin/bash
# Edition : Stable Edition V2.0
# Auther  : Muh Aripin Ilham
# (C) Copyright 2023-2024 By  Under Tunnel
# =========================================
#!/bin/bash
g=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 2)
gb=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 3)
b=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 4)
p=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 5)
r=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 6)
y=$(cat /usr/sbin/mtsc.list | grep "^color" | cut -d " " -f 7)
MYIP=$(wget -qO- ipv4.icanhazip.com);
echo "Loading..."
repo=https://raw.githubusercontent.com/gazzent/ip/main/ip
ipsaya=$(wget -qO- ipv4.icanhazip.com);
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
useexp=$(wget -qO- ${repo} | grep $ipsaya | awk '{print $4}')
if [[ $date_list < $useexp ]]; then
echo -ne
else
echo -e "${g}────────────────────────────────────────────${p}"
echo -e "${b}          404 NOT FOUND AUTOSCRIPT          ${p}"
echo -e "${g}────────────────────────────────────────────${p}"
echo -e ""
echo -e "            ${r}PERMISSION DENIED OR!${p}"
echo -e "   ${y}Your VPS${p} $ipsaya ${y}Expired${p}"
echo -e "     ${y}Buy access permissions for scripts${p}"
echo -e "             ${y}Contact Admin :${p}"
echo -e "      ${gb}Telegram${p} t.me/mehonk_mt"
echo -e "${g}────────────────────────────────────────────${p}"
exit
fi
if [ ! -e /etc/vmess ]; then
mkdir -p /etc/vmess
touch /etc/vmess/.vmess.db
fi
vms=$(cat /etc/vmess/.vmess.db)
if [[ $vms = "" ]]; then
vm="0"
else
vm=$(cat /etc/vmess/.vmess.db | grep "###" | wc -l)
fi
clear
echo -e " ${g}┌──────────────────────────────────────────┐${p}"
echo -e " ${g}│${b}          VMESS MANAGER               ${p}"
echo -e " ${g}└──────────────────────────────────────────┘${p}"
echo -e " ${g}┌──────────────────────────────────────────┐${p}"
echo -e " ${g}│  ${gb}[1]•${p} ${b}Creating a Vmess Account${p}"
echo -e " ${g}│  ${gb}[2]•${p} ${b}Triall a Vmess Account${p}"
echo -e " ${g}│  ${gb}[3]•${p} ${b}Delete Vmess Account${p}"
echo -e " ${g}│  ${gb}[4]•${p} ${b}Renew Vmess Account${p}"
echo -e " ${g}│  ${gb}[5]•${p} ${b}Check Vmess login Account${p}"
echo -e " ${g}│  ${gb}[6]•${p} ${b}Check Info Vmess Config${p}"
echo -e " ${g}└──────────────────────────────────────────┘${p}"
echo -e ""
read -p "   Select From Options [ 1 - 6 ] : " menu
case $menu in
1)
add-vmess
;;
2)
triall-vmess
;;
3)
del vmess
;;
4)
ren vmess
;;
5)
cek vmess
;;
6)
log vmess
;;
*)
menu
;;
esac
