#!/bin/bash
# Edition : Stable Edition V2.0
# Auther  : Muh Aripin Ilham
# (C) Copyright 2023-2024 By  Under Tunnel
# =========================================
#!/bin/bash
repo=https://raw.githubusercontent.com/gazzent/ip/main/ip
ipsaya=$(wget -qO- ipv4.icanhazip.com);
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
useexp=$(wget -qO- ${repo} | grep $ipsaya | awk '{print $4}')
if [[ $date_list < $useexp ]]; then
echo -ne
else
exit
fi
clear
data=($(cat /etc/vmess/.vmess.db| grep '^###' | cut -d ' ' -f 2 | sort | uniq))
now=$(date +"%Y-%m-%d")
for user in "${data[@]}"; do
exp=$(grep -w "^### $user" "/etc/vmess/.vmess.db" | cut -d ' ' -f 3 | sort | uniq)
d1=$(date -d "$exp" +%s)
d2=$(date -d "$now" +%s)
exp2=$(((d1 - d2) / 86400))
if [[ "$exp2" -le "0" ]]; then
sed -i "/^### $user $exp/d" /etc/vmess/.vmess.db
sed -i "/^#vm# $user $exp/,/^},{/d" /etc/xray/config.json
rm /etc/vmess/$user.log >/dev/null
rm /etc/vmess/$user >/dev/null
rm /etc/vmess/cache/$user >/dev/null
rm /var/www/html/vmess-$user.txt >/dev/null
xray api stats --server=127.0.0.1:10000 -name "user>>>${user}>>>traffic>>>downlink" -reset > /dev/null 2>&1
fi
done
data=($(cat /etc/vless/.vless.db| grep '^###' | cut -d ' ' -f 2 | sort | uniq))
now=$(date +"%Y-%m-%d")
for user in "${data[@]}"; do
exp=$(grep -w "^### $user" "/etc/vless/.vless.db" | cut -d ' ' -f 3 | sort | uniq)
d1=$(date -d "$exp" +%s)
d2=$(date -d "$now" +%s)
exp2=$(((d1 - d2) / 86400))
if [[ "$exp2" -le "0" ]]; then
sed -i "/^### $user $exp/d" /etc/vless/.vless.db
sed -i "/^#vl# $user $exp/,/^},{/d" /etc/xray/config.json
rm /etc/vless/$user.log >/dev/null
rm /etc/vless/$user >/dev/null
rm /etc/vless/cache/$user >/dev/null
rm /var/www/html/vless-$user.txt >/dev/null
xray api stats --server=127.0.0.1:10000 -name "user>>>${user}>>>traffic>>>downlink" -reset > /dev/null 2>&1
fi
done
data=($(cat /etc/trojan/.trojan.db| grep '^###' | cut -d ' ' -f 2 | sort | uniq))
now=$(date +"%Y-%m-%d")
for user in "${data[@]}"; do
exp=$(grep -w "^### $user" "/etc/trojan/.trojan.db" | cut -d ' ' -f 3 | sort | uniq)
d1=$(date -d "$exp" +%s)
d2=$(date -d "$now" +%s)
exp2=$(((d1 - d2) / 86400))
if [[ "$exp2" -le "0" ]]; then
sed -i "/^### $user $exp/d" /etc/trojan/.trojan.db
sed -i "/^#tr# $user $exp/,/^},{/d" /etc/xray/config.json
rm /etc/trojan/$user.log >/dev/null
rm /etc/trojan/$user >/dev/null
rm /etc/trojan/cache/$user >/dev/null
rm /var/www/html/trojan-$user.txt >/dev/null
xray api stats --server=127.0.0.1:10000 -name "user>>>${user}>>>traffic>>>downlink" -reset > /dev/null 2>&1
fi
done
data=($(cat /etc/shadowsocks/.shadowsocks.db| grep '^###' | cut -d ' ' -f 2 | sort | uniq))
now=$(date +"%Y-%m-%d")
for user in "${data[@]}"; do
exp=$(grep -w "^### $user" "/etc/shadowsocks/.shadowsocks.db" | cut -d ' ' -f 3 | sort | uniq)
d1=$(date -d "$exp" +%s)
d2=$(date -d "$now" +%s)
exp2=$(((d1 - d2) / 86400))
if [[ "$exp2" -le "0" ]]; then
sed -i "/^### $user $exp/d" /etc/shadowsocks/. shadowsocks.db
sed -i "/^#ss# $user $exp/,/^},{/d" /etc/xray/config.json
rm /etc/shadowsocks/$user.log >/dev/null
rm /etc/shadowsocks/$user >/dev/null
rm /etc/shadowsocks/cache/$user >/dev/null
rm /var/www/html/ss-$user.txt >/dev/null
xray api stats --server=127.0.0.1:10000 -name "user>>>${user}>>>traffic>>>downlink" -reset > /dev/null 2>&1
fi
done
data=($(cat /etc/ssh/.ssh.db| grep '^###' | cut -d ' ' -f 2 | sort | uniq))
now=$(date +"%Y-%m-%d")
for user in "${data[@]}"; do
exp=$(grep -w "^### $user" "/etc/ssh/.ssh.db" | cut -d ' ' -f 3 | sort | uniq)
d1=$(date -d "$exp" +%s)
d2=$(date -d "$now" +%s)
exp2=$(((d1 - d2) / 86400))
if [[ "$exp2" -le "0" ]]; then
userdel --force $user
sed -i "/^### $user $exp/d" /etc/ssh/.ssh.db
rm /etc/ssh/$user.log >/dev/null
rm /etc/ssh/$user >/dev/null
rm /var/www/html/ssh-$user.txt >/dev/null
fi
done
systemctl daemon-reload >/dev/null 2>&1
systemctl restart ssh >/dev/null 2>&1
systemctl restart sshd >/dev/null 2>&1
systemctl restart dropbear >/dev/null 2>&1
systemctl restart xray >/dev/null 2>&1
